### ISSUE TITLE
Babel is broken

### ISSUE THREAD

**Issue by krzysztofpniak** [salsita/redux-elm-skeleton#3]
I've installed newest version and run `npm install`. Everything went ok. After I run npm start I also do not get any errors. Anyways, I have errors in chrome console:
app.bundle.js:16205 Uncaught SyntaxError: Unexpected token import

In fact this bundle fragment seems to not be transpiled be babel:
/**_/ },
/_ 372 */
/***/ function(module, exports) {

```
import run from './boilerplate';

import view from './hello-world/view';
import updater from './hello-world/updater';

run('app', view, updater);
```

/***/ }

**Comment by tomkis** [comment]
Are you sure that you are working on `master` branch? I've tried everything you did but it seems to be working just fine.
